MON-20 add documentaion for device user api endpoint
ustream/api-docs pull request #9
Opened 2017-06-09 12:55 UTC by sziliati

2017-07-04 10:28 UTC, kocsismate requested changes

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +		<p>All of these elements are containing these informations:</p>
"these pieces of information" a helyes, viszont a doksiban a többi helyen ez áll: "Explanation of some values:". Légyszi javítsd a fenti mondatot a channelök listázásánál is!

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>Date of creating</td>
"Creation date"

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>From that time the user can login</td>
"The time after which the device password can be used for logging in."

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>valid_to</td>
valid_until lenne a megfelelő mezőnév

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>Until that time the user can login</td>
"The time until the device password can be used for logging in."

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +		<h6>Positive response example</h6>
Csak "Response" áll a többi a helyen a doksiban. Légyszi javítsd a channel létrehozásánál is a ""Positive response"-t!

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +		<p>The paging information can be found under the "paging" element. Example:</p>
A mondat eleji "The" törölhető!

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +    {
Szerintem elég csak 2 példa!

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>401 Unauthorizedt</td>
"401 Unauthorized"

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td><a href="https://api.ustream.tv/users/self/deviceusers.json">https://api.ustream.tv/users/self/deviceusers.FORMAT</a> (format can be json or xml)</td>
Miért nem "device-passwords" (vagy "devicepasswords") van a "deviceusers" helyett az URL-ben? Nekem ez így furának tűnik.

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +      "valid_to": null
"valid_until"

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +	"previous": ".../users/self/deviceusers.json?pagesize=PAGE_SIZE&page=PREVIOUS_PAGE",
Szerintem a ... zavaró itt, sokkal jobb lenne, ha a teljes URL ki lenne írva, pont úgy, mint a "Listing the user's channels" szakaszban. Légyszi javítsd a ...-ot a "Listing the videos of a channel" és a "Listing the upcoming events of a channel" szakaszban is!

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +		<p>The body of the call should contain the device name and valid from timestamp.</p>
Így helyes: "The body of the call should contain the device name and a "valid_from" timestamp."

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>Until that time the user can login</td>
Ugyanaz, mint fentebb: "The time until the device password can be used for logging in."

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>From that time the user can login</td>
Ugyanaz, mint fentebb: "The time after which the device password can be used for logging in."

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +		<p>All of these elements are containing these informations:</p>
Itt is "Explanation of some values:"

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>Method success</td>
Miért kell visszaadni ezt a mezőt? Máshol nem teszünk említést erről róla. Ha mégis valamiért muszáj lenne megtenni, akkor a "Was the request successful?" érthetőbb leírás.

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +		<h6>Response</h6>
A "Response" alatt általában ez szokott állni a doksiban: "On success a response with HTTP status 200 OK is returned."

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>From that time the user can login</td>
Lásd fentebb

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>Until that time the user can login</td>
Lásd fentebb

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>valid_to</td>
Lásd fentebb

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +		<h6>Positive response example</h6>
Lásd fentebb

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +  "success": true,
Lásd fentebb

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +  "valid_to": "1500249600"
Lásd fentebb

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>If some parameter are missing, or bad request</td>
"In case of any required parameter is missing."

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +		<p>Edit a channel's title, description and tags.</p>
Szerintem ide nincs szükség magyarázatra (de ha szerinted igen, akkor ezt javítsd légyszi, copy-paste hiba van)

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>401 Unauthorizedt</td>
"401 Unauthorized"

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>If deleting fails</td>
"If deletion fails" a helyes, viszont ez nekem inkább 500-as hibakódnak tűnik a leírásból. Szóval jó lenne kicsit pontosítani, hogy milyen esetben lehet gond az inputtal.

2017-07-04 10:28 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td class="verb">POST</td>
Azt hiszem, ide GET kell!

2017-07-04 11:17 UTC, tzetze commented on _posts/2015-09-04-channel.html
> +      "valid_to": null
a unix timestamp adatokat intbe kéne csomagolni

2017-07-04 11:23 UTC, tzetze commented on _posts/2015-09-04-channel.html
> +				<td>If deleting fails</td>
Nem is tudom, az 500-as errorokat külön dokumenbtáljuk-e, vagy csak központilag. Mindenesetre tényleg jó lenne látni, törlésnél milyen user errort lehet elkövetni, aminek 400 a jutalma.

2017-07-04 11:48 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td>If deleting fails</td>
Szerintem külön nem (meg nem is lenne jó, mert akkor kb. minden endpointhoz oda kellene írni, ami felesleges)

2017-07-19 17:44 UTC, kocsismate requested changes

2017-07-19 17:44 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +      "created_at": 1497341340",
bent maradt egy "

2017-07-19 17:44 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +	"previous": ".../users/self/device-passwords.json?pagesize=PAGE_SIZE&page=PREVIOUS_PAGE",
.../ helyett írj légyszi mindenhol https://api.ustream.tv-t

2017-07-20 11:19 UTC, kocsismate requested changes

2017-07-20 11:19 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +	"previous": " https://api.ustream.tv/users/self/device-passwords.json?pagesize=PAGE_SIZE&page=PREVIOUS_PAGE",
Bent maradt egy space itt is meg egy sorral lejjebb is!

2017-07-20 11:19 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +	"previous": " https://api.ustream.tv/CHANNEL_ID/videos.json?pagesize=PAGE_SIZE&page=PREVIOUS_PAGE",
space! :D

2017-07-20 13:57 UTC, kocsismate requested changes

2017-07-20 13:57 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +  "device_users": [
device_passwords

2017-07-20 13:57 UTC, kocsismate commented on _posts/2015-09-04-channel.html
> +				<td><a>https://api.ustream.tv/users/self/device-passwords/DEVICE_NAME.FORMAT</a>format can be json or xml)</td>
USER_NAME lenne jobb a DEVICE_NAME

2017-07-24 13:54 UTC, merged